### PR TITLE
Fixed post 6.43 auth

### PR DESCRIPTION
**Pull request by ArtemKobz**
Hi Martin, 

I've fixed logging in for v6.43+
Please consider merging to base branch.

### CODE REVIEW

**Comment by martin8883** [comment]
Hi Artem,
thank you for PR. I am aware of the problem with the new style auth https://wiki.mikrotik.com/wiki/Manual:API#Initial_login and I will need new style auth in future, too.
But I am also unhappy with this new plain password auth. Your way will work but without looking to code, nobody will be aware that his passwords are now being sent in plain text. So we should add at least a flag confirm_plaintext_password (defaulting to 0) that prevents new auth method unless using SSL or setting this flag to true manually.
Regards
Martin

**Comment by martin8883** [comment]
Can anyone confirm that the old auth style does no longer work for 6.43rc*?
I just started to integrate the new auth method and use a CHR with v.643rc44 as testrouter but old auth method works same way as pre-v6.43?!?

**Comment by martin8883** [comment]
I added your patch to develop branch with addition of a flag (new_auth_method). So we are safe if the old auth method will be removed in future but do not have the plaintext password as long as we do not manually enable new auth method.
https://github.com/martin8883/MikroTik-API/commit/b0f4e6ee30fd9270e76218ad2d0d4ccb9d2e96eb

In my tests v6.43rc44 works flawless with both methods whereas v6.42.6 only works with the old style (as expected.
Could you please also do some tests?

**Comment by ArtemKobz** [comment]
Hi Martin, 

In my tests on multiple routers (CRSes and CCRs) - OLD style auth does NOT work starting from 6.43rc.

You are right - a flag or some kind of warning message is a good idea. Just to be on safe side. 
I'm using API-SSL thus new style auth using plaintext passwords does not really bothers me. 

Thanks!
Artem

**Comment by martin8883** [comment]
Which version do you use? I cannot image it depends on CHR/CRS/CCR/RB/.... But I have to admit that my hardware is on current channel so no chance to test with a CCR or so. Perhaps with an RB2011 in a few days.

In this API project there has been also stated that both login methods are working with  6.43RC32:
https://github.com/socialwifi/RouterOS-api/issues/29

If you are on an older version perhaps Mikrotik has taken into account that plaintext passwords are not always best practice.

Did latest commit in develop branch work for you?

**Comment by bbs2web** [comment]
6.45 depreciates the legacy login method. Herewith a proposed patch which updates API v1.0.5 to work with both:

<pre>--- API.pm.orig 2019-07-08 16:54:31.441655928 +0200
+++ API.pm      2019-07-08 17:09:30.034266534 +0200
@@ -150,21 +150,27 @@
         $self->connect();
     }

+    # RouterOS post v6.43 has new authentication method, pushing login/pass in the very first request. Legacy method has been depreciated since 6.45.
     my @command = ('/login');
+    push( @command, '=name=' . $self->get_username() );
+    push( @command, '=password=' . $self->get_password() );
     my ( $retval, @results ) = $self->talk( \@command );
     if ( $retval > 1 ) {
         die 'error during establishing login: ' . $results[0]{'message'};
     }
-    my $challenge = pack("H*",$results[0]{'ret'});
-    my $md5 = Digest::MD5->new();
-    $md5->add( chr(0) );
-    $md5->add( $self->get_password() );
-    $md5->add( $challenge );
-
-    @command = ('/login');
-    push( @command, '=name=' . $self->get_username() );
-    push( @command, '=response=00' . $md5->hexdigest() );
-    ( $retval, @results ) = $self->talk( \@command );
+    # if we got "=ret=" in response - then assuming this is old style AUTH
+    if ( exists $results[0]{'ret'} ) {
+        my $challenge = pack("H*",$results[0]{'ret'});
+        my $md5 = Digest::MD5->new();
+        $md5->add( chr(0) );
+        $md5->add( $self->get_password() );
+        $md5->add( $challenge );
+
+        @command = ('/login');
+        push( @command, '=name=' . $self->get_username() );
+        push( @command, '=response=00' . $md5->hexdigest() );
+        ( $retval, @results ) = $self->talk( \@command );
+    }
     die 'disconnected while logging in' if !defined $retval;
     if ( $retval > 1 ) {
         die $results[0]{'message'};</pre>

**Pull request closed without merging**
